apiVersion: v2
name: external-dns
description: Automatic DNS record management for Kubernetes
type: application
version: 1.0.0
appVersion: "0.13.2"

dependencies:
  - name: external-dns
    version: 1.12.0
    repository: https://kubernetes-sigs.github.io/external-dns/
