apiVersion: v2
name: cert-manager
description: Automated TLS certificate management for Kubernetes
type: application
version: 1.0.0
appVersion: "v1.11.0"

dependencies:
  - name: cert-manager
    version: v1.11.0
    repository: https://charts.jetstack.io
