apiVersion: v2
name: ingress-nginx
description: NGINX Ingress Controller for Kubernetes
type: application
version: 1.0.0
appVersion: "1.6.4"

dependencies:
  - name: ingress-nginx
    version: 4.5.2
    repository: https://kubernetes.github.io/ingress-nginx
