apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-components

resources:
  - ../base

namePrefix: staging-

commonLabels:
  environment: staging
  managed-by: kustomize

replicas:
  - name: ingress-nginx-controller
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/acme/email
        value: staging-admin@example.com
    target:
      kind: ClusterIssuer
