apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-components

resources:
  - namespace.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.5.2
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: ../../helm/ingress-nginx/values.yaml

  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.11.0
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: ../../helm/cert-manager/values.yaml

  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.12.0
    releaseName: external-dns
    namespace: external-dns
    valuesFile: ../../helm/external-dns/values.yaml

  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.23.0
    releaseName: vault
    namespace: vault
    valuesFile: ../../helm/vault/values.yaml
