apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-components

resources:
  - ../base

namePrefix: prod-

commonLabels:
  environment: production
  managed-by: kustomize

replicas:
  - name: ingress-nginx-controller
    count: 3
  - name: cert-manager
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/acme/email
        value: admin@example.com
    target:
      kind: ClusterIssuer

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
    target:
      kind: Deployment
      name: ingress-nginx-controller
